services:
  postgres_db_dev:
    image: postgres:17.0-alpine
    restart: always
    user: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
      - postgres_dev_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - doctor_appointment_dev_network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-egyahmed.ezzat120@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - doctor_appointment_dev_network

networks:
  doctor_appointment_dev_network:
    name: doctor_appointment_dev_network
    driver: bridge

volumes:
  postgres_dev_data:
  pgadmin:
