spring:
  debug: false
  application:
    name: doctor-appointment-management-system

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true

  liquibase:
    enabled: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB

  messages:
    basename: i18n/messages

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        page-parameter: page
        size-parameter: pageSize
      sort:
        sort-parameter: sort

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    from-name: ${EMAIL_FROM_NAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    test-connection: true
    ssl:
      enabled: true
    properties:
      mail:
        smtp:
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${SECRET_KEY}
core-crud:
  exceptions:
    show-stacktrace: true
#logging:
#  level:
#    org.springframework: DEBUG
#    org.springframework.security: DEBUG
#    com.xorigin.doctorappointmentmanagementsystem: DEBUG
#    root: DEBUG